version: '3.8'

services:
  brazil-blog-web:
    container_name: brazil-blog
    build: .
    command: bash -c "python manage.py migrate && python manage.py bootstrap && python manage.py collectstatic --noinput --ignore brazil_blog.css && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - PYTHON_JIT=1
    volumes:
      - ./src:/code
    ports:
      - 8000:8000
    restart: always
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d  # Your Nginx configuration files
      - /etc/letsencrypt:/etc/letsencrypt  # SSL certificates
      - /var/www/certbot:/var/www/certbot  # Let's Encrypt challenge responses
      - ./src/static:/usr/share/nginx/html/static  # Static files
    depends_on:
      - brazil-blog-web
