# Generated by Django 5.0.4 on 2024-06-03 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blogpagegalleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Post date"
            ),
        ),
    ]
