# Generated by Django 5.0.4 on 2024-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_authorindexpage_blogpage_author_authorpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="video",
            field=models.URLField(null=True),
        ),
    ]
