# Generated by Django 5.0.7 on 2024-08-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_video_squashed_0008_alter_blogpage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='video',
            field=models.URLField(blank=True, help_text='Google drive share link', null=True),
        ),
    ]
