# Generated by Django 5.1.1 on 2024-09-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_likes'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='locations.location'),
        ),
    ]
