# Generated by Django 5.1.1 on 2024-09-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpage_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='location',
        ),
    ]
