# Generated by Django 5.1.1 on 2024-10-06 19:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_itinerarystop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
